//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcKimlikNoileIdariPersonelSorgulaV1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/idaripersonel/2019/05", ConfigurationName="TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelPort")]
    public interface IdariPersonelPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelResponse1> IdariPersonelAsync(TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/idaripersonel/2019/05")]
    public partial class IdariPersonelRequest
    {
        
        private IdariPersonelRequestType idariPersonelBilgiGetirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdariPersonelRequestType IdariPersonelBilgiGetir
        {
            get
            {
                return this.idariPersonelBilgiGetirField;
            }
            set
            {
                this.idariPersonelBilgiGetirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/idaripersonel/2019/05")]
    public partial class IdariPersonelRequestType
    {
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/idaripersonel/2019/05")]
    public partial class ResponseInfoType
    {
        
        private int returnCodeField;
        
        private string externalReturnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string ExternalReturnCode
        {
            get
            {
                return this.externalReturnCodeField;
            }
            set
            {
                this.externalReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/idaripersonel/2019/05")]
    public partial class IdariPersonelResponseType
    {
        
        private long tcKimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private System.Nullable<long> kadroIdField;
        
        private string kadroAdField;
        
        private System.Nullable<long> birimIdField;
        
        private string birimAdField;
        
        private System.Nullable<long> kadroBirimTurField;
        
        private System.Nullable<long> kadroBirimIdField;
        
        private string kadroBirimAdField;
        
        private System.Nullable<long> gorevBirimTurField;
        
        private System.Nullable<long> gorevBirimIdField;
        
        private string gorevBirimAdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> KadroId
        {
            get
            {
                return this.kadroIdField;
            }
            set
            {
                this.kadroIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string KadroAd
        {
            get
            {
                return this.kadroAdField;
            }
            set
            {
                this.kadroAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> BirimId
        {
            get
            {
                return this.birimIdField;
            }
            set
            {
                this.birimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string BirimAd
        {
            get
            {
                return this.birimAdField;
            }
            set
            {
                this.birimAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> KadroBirimTur
        {
            get
            {
                return this.kadroBirimTurField;
            }
            set
            {
                this.kadroBirimTurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> KadroBirimId
        {
            get
            {
                return this.kadroBirimIdField;
            }
            set
            {
                this.kadroBirimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string KadroBirimAd
        {
            get
            {
                return this.kadroBirimAdField;
            }
            set
            {
                this.kadroBirimAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<long> GorevBirimTur
        {
            get
            {
                return this.gorevBirimTurField;
            }
            set
            {
                this.gorevBirimTurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<long> GorevBirimId
        {
            get
            {
                return this.gorevBirimIdField;
            }
            set
            {
                this.gorevBirimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string GorevBirimAd
        {
            get
            {
                return this.gorevBirimAdField;
            }
            set
            {
                this.gorevBirimAdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/idaripersonel/2019/05")]
    public partial class IdariPersonelResponse
    {
        
        private IdariPersonelResponseType idariPersonelField;
        
        private ResponseInfoType sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdariPersonelResponseType IdariPersonel
        {
            get
            {
                return this.idariPersonelField;
            }
            set
            {
                this.idariPersonelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseInfoType Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdariPersonelRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/idaripersonel/2019/05", Order=0)]
        public TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest IdariPersonelRequest;
        
        public IdariPersonelRequest1()
        {
        }
        
        public IdariPersonelRequest1(TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest IdariPersonelRequest)
        {
            this.IdariPersonelRequest = IdariPersonelRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdariPersonelResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/idaripersonel/2019/05", Order=0)]
        public TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelResponse IdariPersonelResponse;
        
        public IdariPersonelResponse1()
        {
        }
        
        public IdariPersonelResponse1(TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelResponse IdariPersonelResponse)
        {
            this.IdariPersonelResponse = IdariPersonelResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IdariPersonelPortChannel : TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IdariPersonelPortClient : System.ServiceModel.ClientBase<TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelPort>, TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IdariPersonelPortClient() : 
                base(IdariPersonelPortClient.GetDefaultBinding(), IdariPersonelPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IdariPersonelPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdariPersonelPortClient(EndpointConfiguration endpointConfiguration) : 
                base(IdariPersonelPortClient.GetBindingForEndpoint(endpointConfiguration), IdariPersonelPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdariPersonelPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IdariPersonelPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdariPersonelPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IdariPersonelPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdariPersonelPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelResponse1> TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelPort.IdariPersonelAsync(TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest1 request)
        {
            return base.Channel.IdariPersonelAsync(request);
        }
        
        public System.Threading.Tasks.Task<TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelResponse1> IdariPersonelAsync(TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest IdariPersonelRequest)
        {
            TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest1 inValue = new TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelRequest1();
            inValue.IdariPersonelRequest = IdariPersonelRequest;
            return ((TcKimlikNoileIdariPersonelSorgulaV1.IdariPersonelPort)(this)).IdariPersonelAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IdariPersonelPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IdariPersonelPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://servis.turkiye.gov.tr/services/g2g/yok/tckimliknoileidaripersonelsorgulav" +
                        "1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IdariPersonelPortClient.GetBindingForEndpoint(EndpointConfiguration.IdariPersonelPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IdariPersonelPortClient.GetEndpointAddress(EndpointConfiguration.IdariPersonelPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            IdariPersonelPortSoap11,
        }
    }
}
