//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKYS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CKYS.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UetsDrTckn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.DoktorList UetsDrTckn(string Kullanici, string Parola, string Tckn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UetsDrTckn", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.DoktorList> UetsDrTcknAsync(string Kullanici, string Parola, string Tckn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UetsDrKurum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.KurumList UetsDrKurum(string Kullanici, string Parola, string KurumKod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UetsDrKurum", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.KurumList> UetsDrKurumAsync(string Kullanici, string Parola, string KurumKod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UetsKurumList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.KurumlarListesi UetsKurumList(string Kullanici, string Parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UetsKurumList", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.KurumlarListesi> UetsKurumListAsync(string Kullanici, string Parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IzinBilgisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.IzinBilgiList IzinBilgisi(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IzinBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.IzinBilgiList> IzinBilgisiAsync(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AyrilisBaslayisBilgisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.AyrilisBaslayisList AyrilisBaslayisBilgisi(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AyrilisBaslayisBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.AyrilisBaslayisList> AyrilisBaslayisBilgisiAsync(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonUzmanlikTarihi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.SonUzmanlikList SonUzmanlikTarihi(string Kullanici, string Parola, string Mernis, string KurumNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonUzmanlikTarihi", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.SonUzmanlikList> SonUzmanlikTarihiAsync(string Kullanici, string Parola, string Mernis, string KurumNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonelAyrBaslTarihBilgisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.PerAyrilisBaslayisList PersonelAyrBaslTarihBilgisi(string Kullanici, string Parola, string Mernis, string KurumNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonelAyrBaslTarihBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.PerAyrilisBaslayisList> PersonelAyrBaslTarihBilgisiAsync(string Kullanici, string Parola, string Mernis, string KurumNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrTahsilBilgisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CKYS.DrKayitDoktorList DrTahsilBilgisi(string Kullanici, string Parola, string Mernis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrTahsilBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<CKYS.DrKayitDoktorList> DrTahsilBilgisiAsync(string Kullanici, string Parola, string Mernis);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DoktorList
    {
        
        private IslemKontrol islemField;
        
        private UetsAlan[] drListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public UetsAlan[] DrList
        {
            get
            {
                return this.drListField;
            }
            set
            {
                this.drListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IslemKontrol
    {
        
        private int sonucField;
        
        private string degerField;
        
        private string bilgiField;
        
        private string hataField;
        
        private string ipField;
        
        private IslemKontrolDT dtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string deger
        {
            get
            {
                return this.degerField;
            }
            set
            {
                this.degerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bilgi
        {
            get
            {
                return this.bilgiField;
            }
            set
            {
                this.bilgiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string hata
        {
            get
            {
                return this.hataField;
            }
            set
            {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ip
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public IslemKontrolDT dt
        {
            get
            {
                return this.dtField;
            }
            set
            {
                this.dtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class IslemKontrolDT
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrKayitDoktor
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IslemKontrolDr
    {
        
        private int adetField;
        
        private string tahsil_turuField;
        
        private int sonucField;
        
        private string degerField;
        
        private string bilgiField;
        
        private string hataField;
        
        private string ipField;
        
        private IslemKontrolDrDT dtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int adet
        {
            get
            {
                return this.adetField;
            }
            set
            {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tahsil_turu
        {
            get
            {
                return this.tahsil_turuField;
            }
            set
            {
                this.tahsil_turuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deger
        {
            get
            {
                return this.degerField;
            }
            set
            {
                this.degerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bilgi
        {
            get
            {
                return this.bilgiField;
            }
            set
            {
                this.bilgiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string hata
        {
            get
            {
                return this.hataField;
            }
            set
            {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ip
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public IslemKontrolDrDT dt
        {
            get
            {
                return this.dtField;
            }
            set
            {
                this.dtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class IslemKontrolDrDT
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrKayitDoktorList
    {
        
        private IslemKontrolDr islemField;
        
        private DrKayitDoktor[] drListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrolDr Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public DrKayitDoktor[] drList
        {
            get
            {
                return this.drListField;
            }
            set
            {
                this.drListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerAyrilisBaslayis
    {
        
        private string ackField;
        
        private string birim_Sira_NoField;
        
        private string grv_Bsl_TrhField;
        
        private string grv_Ayr_TrhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ack
        {
            get
            {
                return this.ackField;
            }
            set
            {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Birim_Sira_No
        {
            get
            {
                return this.birim_Sira_NoField;
            }
            set
            {
                this.birim_Sira_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Grv_Bsl_Trh
        {
            get
            {
                return this.grv_Bsl_TrhField;
            }
            set
            {
                this.grv_Bsl_TrhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Grv_Ayr_Trh
        {
            get
            {
                return this.grv_Ayr_TrhField;
            }
            set
            {
                this.grv_Ayr_TrhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerAyrilisBaslayisList
    {
        
        private IslemKontrol islemField;
        
        private PerAyrilisBaslayis[] perAyrBslListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public PerAyrilisBaslayis[] PerAyrBslList
        {
            get
            {
                return this.perAyrBslListField;
            }
            set
            {
                this.perAyrBslListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SonUzmanlik
    {
        
        private string uzmanlik_bsl_tarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uzmanlik_bsl_tarihi
        {
            get
            {
                return this.uzmanlik_bsl_tarihiField;
            }
            set
            {
                this.uzmanlik_bsl_tarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SonUzmanlikList
    {
        
        private IslemKontrol islemField;
        
        private SonUzmanlik[] sonUzmListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SonUzmanlik[] SonUzmList
        {
            get
            {
                return this.sonUzmListField;
            }
            set
            {
                this.sonUzmListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AyrilisBaslayis
    {
        
        private string tcknField;
        
        private string grv_bsl_trhField;
        
        private string grv_ayr_trhField;
        
        private string birim_sira_noField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tckn
        {
            get
            {
                return this.tcknField;
            }
            set
            {
                this.tcknField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string grv_bsl_trh
        {
            get
            {
                return this.grv_bsl_trhField;
            }
            set
            {
                this.grv_bsl_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string grv_ayr_trh
        {
            get
            {
                return this.grv_ayr_trhField;
            }
            set
            {
                this.grv_ayr_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string birim_sira_no
        {
            get
            {
                return this.birim_sira_noField;
            }
            set
            {
                this.birim_sira_noField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AyrilisBaslayisList
    {
        
        private IslemKontrol islemField;
        
        private AyrilisBaslayis[] ayBasListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public AyrilisBaslayis[] AyBasList
        {
            get
            {
                return this.ayBasListField;
            }
            set
            {
                this.ayBasListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IzinBilgi
    {
        
        private string tcknField;
        
        private string hareket_turu_ackField;
        
        private string hareket_turu_idField;
        
        private string hareket_baslama_tarhField;
        
        private string hareket_bitis_trhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tckn
        {
            get
            {
                return this.tcknField;
            }
            set
            {
                this.tcknField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string hareket_turu_ack
        {
            get
            {
                return this.hareket_turu_ackField;
            }
            set
            {
                this.hareket_turu_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hareket_turu_id
        {
            get
            {
                return this.hareket_turu_idField;
            }
            set
            {
                this.hareket_turu_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string hareket_baslama_tarh
        {
            get
            {
                return this.hareket_baslama_tarhField;
            }
            set
            {
                this.hareket_baslama_tarhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string hareket_bitis_trh
        {
            get
            {
                return this.hareket_bitis_trhField;
            }
            set
            {
                this.hareket_bitis_trhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IzinBilgiList
    {
        
        private IslemKontrol islemField;
        
        private IzinBilgi[] izinListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public IzinBilgi[] IzinList
        {
            get
            {
                return this.izinListField;
            }
            set
            {
                this.izinListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UetsKurumAlan
    {
        
        private string kurum_NoField;
        
        private string kurum_AdField;
        
        private string il_KodField;
        
        private string ilce_KodField;
        
        private string std_Br_KoduField;
        
        private string ckys_Kurum_turuField;
        
        private string kurum_TipiField;
        
        private string ckys_Kurum_TipiField;
        
        private string kurum_TuruField;
        
        private string afiliyeField;
        
        private string afiliye_Kurum_KodField;
        
        private string afiliye_Kurum_AdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Kurum_No
        {
            get
            {
                return this.kurum_NoField;
            }
            set
            {
                this.kurum_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kurum_Ad
        {
            get
            {
                return this.kurum_AdField;
            }
            set
            {
                this.kurum_AdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Il_Kod
        {
            get
            {
                return this.il_KodField;
            }
            set
            {
                this.il_KodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ilce_Kod
        {
            get
            {
                return this.ilce_KodField;
            }
            set
            {
                this.ilce_KodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Std_Br_Kodu
        {
            get
            {
                return this.std_Br_KoduField;
            }
            set
            {
                this.std_Br_KoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Ckys_Kurum_turu
        {
            get
            {
                return this.ckys_Kurum_turuField;
            }
            set
            {
                this.ckys_Kurum_turuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Kurum_Tipi
        {
            get
            {
                return this.kurum_TipiField;
            }
            set
            {
                this.kurum_TipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Ckys_Kurum_Tipi
        {
            get
            {
                return this.ckys_Kurum_TipiField;
            }
            set
            {
                this.ckys_Kurum_TipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Kurum_Turu
        {
            get
            {
                return this.kurum_TuruField;
            }
            set
            {
                this.kurum_TuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Afiliye
        {
            get
            {
                return this.afiliyeField;
            }
            set
            {
                this.afiliyeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Afiliye_Kurum_Kod
        {
            get
            {
                return this.afiliye_Kurum_KodField;
            }
            set
            {
                this.afiliye_Kurum_KodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Afiliye_Kurum_Ad
        {
            get
            {
                return this.afiliye_Kurum_AdField;
            }
            set
            {
                this.afiliye_Kurum_AdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KurumlarListesi
    {
        
        private IslemKontrol islemField;
        
        private UetsKurumAlan[] kurumlarListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public UetsKurumAlan[] KurumlarList
        {
            get
            {
                return this.kurumlarListField;
            }
            set
            {
                this.kurumlarListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KurumList
    {
        
        private IslemKontrol islemField;
        
        private UetsAlan[] kurumVListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IslemKontrol Islem
        {
            get
            {
                return this.islemField;
            }
            set
            {
                this.islemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public UetsAlan[] KurumVList
        {
            get
            {
                return this.kurumVListField;
            }
            set
            {
                this.kurumVListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UetsAlan
    {
        
        private string mernis_noField;
        
        private string psnField;
        
        private string adField;
        
        private string soyadField;
        
        private string v_aktif_birim_kodField;
        
        private string v_aktif_birim_adField;
        
        private string v_gecici_gorev_birim_kodField;
        
        private string v_gecici_gorev_birim_adField;
        
        private string v_calisma_durumuField;
        
        private string v_aktif_unvan_kodField;
        
        private string v_aktif_unvan_adField;
        
        private string v_ihtisas_unvan_kodField;
        
        private string v_ihtisas_unvan_adField;
        
        private string v_ogrencimiField;
        
        private string v_basasistan_olma_trhField;
        
        private string dhk_mezun_okulField;
        
        private string dhk_tescil_noField;
        
        private string dhk_tescil_trhField;
        
        private string dhk_dip_noField;
        
        private string dhk_meslek_unvaniField;
        
        private string tip_mezun_okulField;
        
        private string tip_tescil_noField;
        
        private string tip_tescil_trhField;
        
        private string tip_dip_noField;
        
        private string tip_meslek_unvaniField;
        
        private string uzm1_tescil_noField;
        
        private string uzm1_tescil_trhField;
        
        private string uzm1_brans_koduField;
        
        private string uzm1_brans_adiField;
        
        private string uzm1_mezun_okulField;
        
        private string uzm1_meslek_unvaniField;
        
        private string uzm2_tescil_noField;
        
        private string uzm2_tescil_trhField;
        
        private string uzm2_brans_koduField;
        
        private string uzm2_brans_adiField;
        
        private string uzm2_mezun_okulField;
        
        private string uzm2_meslek_unvaniField;
        
        private string uzm3_tescil_noField;
        
        private string uzm3_tescil_trhField;
        
        private string uzm3_brans_koduField;
        
        private string uzm3_brans_adiField;
        
        private string uzm3_mezun_okulField;
        
        private string uzm3_meslek_unvaniField;
        
        private string uzm4_tescil_noField;
        
        private string uzm4_tescil_trhField;
        
        private string uzm4_brans_koduField;
        
        private string uzm4_brans_adiField;
        
        private string uzm4_mezun_okulField;
        
        private string uzm4_meslek_unvaniField;
        
        private string uzm5_tescil_noField;
        
        private string uzm5_tescil_trhField;
        
        private string uzm5_brans_koduField;
        
        private string uzm5_brans_adiField;
        
        private string uzm5_mezun_okulField;
        
        private string uzm5_meslek_unvaniField;
        
        private string tescil_trhField;
        
        private string guncelleme_trhField;
        
        private string dhk_iptal_trhField;
        
        private string dhk_iptal_sebepField;
        
        private string dhk_iptal_ackField;
        
        private string tip_iptal_trhField;
        
        private string tip_iptal_sebepField;
        
        private string tip_iptal_ackField;
        
        private string uzm1_iptal_trhField;
        
        private string uzm1_iptal_sebepField;
        
        private string uzm1_iptal_ackField;
        
        private string uzm2_iptal_trhField;
        
        private string uzm2_iptal_sebepField;
        
        private string uzm2_iptal_ackField;
        
        private string uzm3_iptal_trhField;
        
        private string uzm3_iptal_sebepField;
        
        private string uzm3_iptal_ackField;
        
        private string uzm4_iptal_trhField;
        
        private string uzm4_iptal_sebepField;
        
        private string uzm4_iptal_ackField;
        
        private string uzm5_iptal_trhField;
        
        private string uzm5_iptal_sebepField;
        
        private string uzm5_iptal_ackField;
        
        private string dhk_mez_trhField;
        
        private string tip_mez_trhField;
        
        private string uzm1_mez_trhField;
        
        private string uzm2_mez_trhField;
        
        private string uzm3_mez_trhField;
        
        private string uzm4_mez_trhField;
        
        private string uzm5_mez_trhField;
        
        private string kayit_seqField;
        
        private string sorgu_trhField;
        
        private string tip_mezun_fakulteField;
        
        private string dhk_mezun_fakulteField;
        
        private string emailField;
        
        private string cep_noField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mernis_no
        {
            get
            {
                return this.mernis_noField;
            }
            set
            {
                this.mernis_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string psn
        {
            get
            {
                return this.psnField;
            }
            set
            {
                this.psnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string v_aktif_birim_kod
        {
            get
            {
                return this.v_aktif_birim_kodField;
            }
            set
            {
                this.v_aktif_birim_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string v_aktif_birim_ad
        {
            get
            {
                return this.v_aktif_birim_adField;
            }
            set
            {
                this.v_aktif_birim_adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string v_gecici_gorev_birim_kod
        {
            get
            {
                return this.v_gecici_gorev_birim_kodField;
            }
            set
            {
                this.v_gecici_gorev_birim_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string v_gecici_gorev_birim_ad
        {
            get
            {
                return this.v_gecici_gorev_birim_adField;
            }
            set
            {
                this.v_gecici_gorev_birim_adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string v_calisma_durumu
        {
            get
            {
                return this.v_calisma_durumuField;
            }
            set
            {
                this.v_calisma_durumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string v_aktif_unvan_kod
        {
            get
            {
                return this.v_aktif_unvan_kodField;
            }
            set
            {
                this.v_aktif_unvan_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string v_aktif_unvan_ad
        {
            get
            {
                return this.v_aktif_unvan_adField;
            }
            set
            {
                this.v_aktif_unvan_adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string v_ihtisas_unvan_kod
        {
            get
            {
                return this.v_ihtisas_unvan_kodField;
            }
            set
            {
                this.v_ihtisas_unvan_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string v_ihtisas_unvan_ad
        {
            get
            {
                return this.v_ihtisas_unvan_adField;
            }
            set
            {
                this.v_ihtisas_unvan_adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string v_ogrencimi
        {
            get
            {
                return this.v_ogrencimiField;
            }
            set
            {
                this.v_ogrencimiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string v_basasistan_olma_trh
        {
            get
            {
                return this.v_basasistan_olma_trhField;
            }
            set
            {
                this.v_basasistan_olma_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string dhk_mezun_okul
        {
            get
            {
                return this.dhk_mezun_okulField;
            }
            set
            {
                this.dhk_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string dhk_tescil_no
        {
            get
            {
                return this.dhk_tescil_noField;
            }
            set
            {
                this.dhk_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string dhk_tescil_trh
        {
            get
            {
                return this.dhk_tescil_trhField;
            }
            set
            {
                this.dhk_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string dhk_dip_no
        {
            get
            {
                return this.dhk_dip_noField;
            }
            set
            {
                this.dhk_dip_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string dhk_meslek_unvani
        {
            get
            {
                return this.dhk_meslek_unvaniField;
            }
            set
            {
                this.dhk_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string tip_mezun_okul
        {
            get
            {
                return this.tip_mezun_okulField;
            }
            set
            {
                this.tip_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string tip_tescil_no
        {
            get
            {
                return this.tip_tescil_noField;
            }
            set
            {
                this.tip_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string tip_tescil_trh
        {
            get
            {
                return this.tip_tescil_trhField;
            }
            set
            {
                this.tip_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string tip_dip_no
        {
            get
            {
                return this.tip_dip_noField;
            }
            set
            {
                this.tip_dip_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string tip_meslek_unvani
        {
            get
            {
                return this.tip_meslek_unvaniField;
            }
            set
            {
                this.tip_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string uzm1_tescil_no
        {
            get
            {
                return this.uzm1_tescil_noField;
            }
            set
            {
                this.uzm1_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string uzm1_tescil_trh
        {
            get
            {
                return this.uzm1_tescil_trhField;
            }
            set
            {
                this.uzm1_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string uzm1_brans_kodu
        {
            get
            {
                return this.uzm1_brans_koduField;
            }
            set
            {
                this.uzm1_brans_koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string uzm1_brans_adi
        {
            get
            {
                return this.uzm1_brans_adiField;
            }
            set
            {
                this.uzm1_brans_adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string uzm1_mezun_okul
        {
            get
            {
                return this.uzm1_mezun_okulField;
            }
            set
            {
                this.uzm1_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string uzm1_meslek_unvani
        {
            get
            {
                return this.uzm1_meslek_unvaniField;
            }
            set
            {
                this.uzm1_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string uzm2_tescil_no
        {
            get
            {
                return this.uzm2_tescil_noField;
            }
            set
            {
                this.uzm2_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string uzm2_tescil_trh
        {
            get
            {
                return this.uzm2_tescil_trhField;
            }
            set
            {
                this.uzm2_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string uzm2_brans_kodu
        {
            get
            {
                return this.uzm2_brans_koduField;
            }
            set
            {
                this.uzm2_brans_koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string uzm2_brans_adi
        {
            get
            {
                return this.uzm2_brans_adiField;
            }
            set
            {
                this.uzm2_brans_adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string uzm2_mezun_okul
        {
            get
            {
                return this.uzm2_mezun_okulField;
            }
            set
            {
                this.uzm2_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string uzm2_meslek_unvani
        {
            get
            {
                return this.uzm2_meslek_unvaniField;
            }
            set
            {
                this.uzm2_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string uzm3_tescil_no
        {
            get
            {
                return this.uzm3_tescil_noField;
            }
            set
            {
                this.uzm3_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string uzm3_tescil_trh
        {
            get
            {
                return this.uzm3_tescil_trhField;
            }
            set
            {
                this.uzm3_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string uzm3_brans_kodu
        {
            get
            {
                return this.uzm3_brans_koduField;
            }
            set
            {
                this.uzm3_brans_koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string uzm3_brans_adi
        {
            get
            {
                return this.uzm3_brans_adiField;
            }
            set
            {
                this.uzm3_brans_adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string uzm3_mezun_okul
        {
            get
            {
                return this.uzm3_mezun_okulField;
            }
            set
            {
                this.uzm3_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string uzm3_meslek_unvani
        {
            get
            {
                return this.uzm3_meslek_unvaniField;
            }
            set
            {
                this.uzm3_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string uzm4_tescil_no
        {
            get
            {
                return this.uzm4_tescil_noField;
            }
            set
            {
                this.uzm4_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string uzm4_tescil_trh
        {
            get
            {
                return this.uzm4_tescil_trhField;
            }
            set
            {
                this.uzm4_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string uzm4_brans_kodu
        {
            get
            {
                return this.uzm4_brans_koduField;
            }
            set
            {
                this.uzm4_brans_koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string uzm4_brans_adi
        {
            get
            {
                return this.uzm4_brans_adiField;
            }
            set
            {
                this.uzm4_brans_adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string uzm4_mezun_okul
        {
            get
            {
                return this.uzm4_mezun_okulField;
            }
            set
            {
                this.uzm4_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string uzm4_meslek_unvani
        {
            get
            {
                return this.uzm4_meslek_unvaniField;
            }
            set
            {
                this.uzm4_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string uzm5_tescil_no
        {
            get
            {
                return this.uzm5_tescil_noField;
            }
            set
            {
                this.uzm5_tescil_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string uzm5_tescil_trh
        {
            get
            {
                return this.uzm5_tescil_trhField;
            }
            set
            {
                this.uzm5_tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string uzm5_brans_kodu
        {
            get
            {
                return this.uzm5_brans_koduField;
            }
            set
            {
                this.uzm5_brans_koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string uzm5_brans_adi
        {
            get
            {
                return this.uzm5_brans_adiField;
            }
            set
            {
                this.uzm5_brans_adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string uzm5_mezun_okul
        {
            get
            {
                return this.uzm5_mezun_okulField;
            }
            set
            {
                this.uzm5_mezun_okulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string uzm5_meslek_unvani
        {
            get
            {
                return this.uzm5_meslek_unvaniField;
            }
            set
            {
                this.uzm5_meslek_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string tescil_trh
        {
            get
            {
                return this.tescil_trhField;
            }
            set
            {
                this.tescil_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string guncelleme_trh
        {
            get
            {
                return this.guncelleme_trhField;
            }
            set
            {
                this.guncelleme_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string dhk_iptal_trh
        {
            get
            {
                return this.dhk_iptal_trhField;
            }
            set
            {
                this.dhk_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string dhk_iptal_sebep
        {
            get
            {
                return this.dhk_iptal_sebepField;
            }
            set
            {
                this.dhk_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string dhk_iptal_ack
        {
            get
            {
                return this.dhk_iptal_ackField;
            }
            set
            {
                this.dhk_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string tip_iptal_trh
        {
            get
            {
                return this.tip_iptal_trhField;
            }
            set
            {
                this.tip_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string tip_iptal_sebep
        {
            get
            {
                return this.tip_iptal_sebepField;
            }
            set
            {
                this.tip_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string tip_iptal_ack
        {
            get
            {
                return this.tip_iptal_ackField;
            }
            set
            {
                this.tip_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string uzm1_iptal_trh
        {
            get
            {
                return this.uzm1_iptal_trhField;
            }
            set
            {
                this.uzm1_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string uzm1_iptal_sebep
        {
            get
            {
                return this.uzm1_iptal_sebepField;
            }
            set
            {
                this.uzm1_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string uzm1_iptal_ack
        {
            get
            {
                return this.uzm1_iptal_ackField;
            }
            set
            {
                this.uzm1_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string uzm2_iptal_trh
        {
            get
            {
                return this.uzm2_iptal_trhField;
            }
            set
            {
                this.uzm2_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string uzm2_iptal_sebep
        {
            get
            {
                return this.uzm2_iptal_sebepField;
            }
            set
            {
                this.uzm2_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string uzm2_iptal_ack
        {
            get
            {
                return this.uzm2_iptal_ackField;
            }
            set
            {
                this.uzm2_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string uzm3_iptal_trh
        {
            get
            {
                return this.uzm3_iptal_trhField;
            }
            set
            {
                this.uzm3_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string uzm3_iptal_sebep
        {
            get
            {
                return this.uzm3_iptal_sebepField;
            }
            set
            {
                this.uzm3_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string uzm3_iptal_ack
        {
            get
            {
                return this.uzm3_iptal_ackField;
            }
            set
            {
                this.uzm3_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string uzm4_iptal_trh
        {
            get
            {
                return this.uzm4_iptal_trhField;
            }
            set
            {
                this.uzm4_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string uzm4_iptal_sebep
        {
            get
            {
                return this.uzm4_iptal_sebepField;
            }
            set
            {
                this.uzm4_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string uzm4_iptal_ack
        {
            get
            {
                return this.uzm4_iptal_ackField;
            }
            set
            {
                this.uzm4_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string uzm5_iptal_trh
        {
            get
            {
                return this.uzm5_iptal_trhField;
            }
            set
            {
                this.uzm5_iptal_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public string uzm5_iptal_sebep
        {
            get
            {
                return this.uzm5_iptal_sebepField;
            }
            set
            {
                this.uzm5_iptal_sebepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string uzm5_iptal_ack
        {
            get
            {
                return this.uzm5_iptal_ackField;
            }
            set
            {
                this.uzm5_iptal_ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public string dhk_mez_trh
        {
            get
            {
                return this.dhk_mez_trhField;
            }
            set
            {
                this.dhk_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public string tip_mez_trh
        {
            get
            {
                return this.tip_mez_trhField;
            }
            set
            {
                this.tip_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public string uzm1_mez_trh
        {
            get
            {
                return this.uzm1_mez_trhField;
            }
            set
            {
                this.uzm1_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=81)]
        public string uzm2_mez_trh
        {
            get
            {
                return this.uzm2_mez_trhField;
            }
            set
            {
                this.uzm2_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=82)]
        public string uzm3_mez_trh
        {
            get
            {
                return this.uzm3_mez_trhField;
            }
            set
            {
                this.uzm3_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public string uzm4_mez_trh
        {
            get
            {
                return this.uzm4_mez_trhField;
            }
            set
            {
                this.uzm4_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=84)]
        public string uzm5_mez_trh
        {
            get
            {
                return this.uzm5_mez_trhField;
            }
            set
            {
                this.uzm5_mez_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=85)]
        public string kayit_seq
        {
            get
            {
                return this.kayit_seqField;
            }
            set
            {
                this.kayit_seqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=86)]
        public string sorgu_trh
        {
            get
            {
                return this.sorgu_trhField;
            }
            set
            {
                this.sorgu_trhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=87)]
        public string tip_mezun_fakulte
        {
            get
            {
                return this.tip_mezun_fakulteField;
            }
            set
            {
                this.tip_mezun_fakulteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=88)]
        public string dhk_mezun_fakulte
        {
            get
            {
                return this.dhk_mezun_fakulteField;
            }
            set
            {
                this.dhk_mezun_fakulteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=89)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=90)]
        public string cep_no
        {
            get
            {
                return this.cep_noField;
            }
            set
            {
                this.cep_noField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface Service1SoapChannel : CKYS.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<CKYS.Service1Soap>, CKYS.Service1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CKYS.DoktorList UetsDrTckn(string Kullanici, string Parola, string Tckn)
        {
            return base.Channel.UetsDrTckn(Kullanici, Parola, Tckn);
        }
        
        public System.Threading.Tasks.Task<CKYS.DoktorList> UetsDrTcknAsync(string Kullanici, string Parola, string Tckn)
        {
            return base.Channel.UetsDrTcknAsync(Kullanici, Parola, Tckn);
        }
        
        public CKYS.KurumList UetsDrKurum(string Kullanici, string Parola, string KurumKod)
        {
            return base.Channel.UetsDrKurum(Kullanici, Parola, KurumKod);
        }
        
        public System.Threading.Tasks.Task<CKYS.KurumList> UetsDrKurumAsync(string Kullanici, string Parola, string KurumKod)
        {
            return base.Channel.UetsDrKurumAsync(Kullanici, Parola, KurumKod);
        }
        
        public CKYS.KurumlarListesi UetsKurumList(string Kullanici, string Parola)
        {
            return base.Channel.UetsKurumList(Kullanici, Parola);
        }
        
        public System.Threading.Tasks.Task<CKYS.KurumlarListesi> UetsKurumListAsync(string Kullanici, string Parola)
        {
            return base.Channel.UetsKurumListAsync(Kullanici, Parola);
        }
        
        public CKYS.IzinBilgiList IzinBilgisi(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2)
        {
            return base.Channel.IzinBilgisi(Kullanici, Parola, Mernis, Tarih1, Tarih2);
        }
        
        public System.Threading.Tasks.Task<CKYS.IzinBilgiList> IzinBilgisiAsync(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2)
        {
            return base.Channel.IzinBilgisiAsync(Kullanici, Parola, Mernis, Tarih1, Tarih2);
        }
        
        public CKYS.AyrilisBaslayisList AyrilisBaslayisBilgisi(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2)
        {
            return base.Channel.AyrilisBaslayisBilgisi(Kullanici, Parola, Mernis, Tarih1, Tarih2);
        }
        
        public System.Threading.Tasks.Task<CKYS.AyrilisBaslayisList> AyrilisBaslayisBilgisiAsync(string Kullanici, string Parola, string Mernis, string Tarih1, string Tarih2)
        {
            return base.Channel.AyrilisBaslayisBilgisiAsync(Kullanici, Parola, Mernis, Tarih1, Tarih2);
        }
        
        public CKYS.SonUzmanlikList SonUzmanlikTarihi(string Kullanici, string Parola, string Mernis, string KurumNo)
        {
            return base.Channel.SonUzmanlikTarihi(Kullanici, Parola, Mernis, KurumNo);
        }
        
        public System.Threading.Tasks.Task<CKYS.SonUzmanlikList> SonUzmanlikTarihiAsync(string Kullanici, string Parola, string Mernis, string KurumNo)
        {
            return base.Channel.SonUzmanlikTarihiAsync(Kullanici, Parola, Mernis, KurumNo);
        }
        
        public CKYS.PerAyrilisBaslayisList PersonelAyrBaslTarihBilgisi(string Kullanici, string Parola, string Mernis, string KurumNo)
        {
            return base.Channel.PersonelAyrBaslTarihBilgisi(Kullanici, Parola, Mernis, KurumNo);
        }
        
        public System.Threading.Tasks.Task<CKYS.PerAyrilisBaslayisList> PersonelAyrBaslTarihBilgisiAsync(string Kullanici, string Parola, string Mernis, string KurumNo)
        {
            return base.Channel.PersonelAyrBaslTarihBilgisiAsync(Kullanici, Parola, Mernis, KurumNo);
        }
        
        public CKYS.DrKayitDoktorList DrTahsilBilgisi(string Kullanici, string Parola, string Mernis)
        {
            return base.Channel.DrTahsilBilgisi(Kullanici, Parola, Mernis);
        }
        
        public System.Threading.Tasks.Task<CKYS.DrKayitDoktorList> DrTahsilBilgisiAsync(string Kullanici, string Parola, string Mernis)
        {
            return base.Channel.DrTahsilBilgisiAsync(Kullanici, Parola, Mernis);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://ckysweb.saglik.gov.tr/UETSWs/Service1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ckysweb.saglik.gov.tr/UETSWs/Service1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
}
