//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03", ConfigurationName="TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersone" +
        "lPort")]
    public interface AkademikveIdariPersonelPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelResponse1> AkademikveIdariPersonelAsync(TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class AkademikveIdariPersonelRequest
    {
        
        private AkademikveIdariPersonelRequestType akademikveIdariPersonelBilgiGetirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AkademikveIdariPersonelRequestType AkademikveIdariPersonelBilgiGetir
        {
            get
            {
                return this.akademikveIdariPersonelBilgiGetirField;
            }
            set
            {
                this.akademikveIdariPersonelBilgiGetirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class AkademikveIdariPersonelRequestType
    {
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class ResponseInfoType
    {
        
        private int returnCodeField;
        
        private string externalReturnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string ExternalReturnCode
        {
            get
            {
                return this.externalReturnCodeField;
            }
            set
            {
                this.externalReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class GorevlendirmeBilgi
    {
        
        private string gorevTurField;
        
        private long gorevBirimField;
        
        private bool gorevBirimFieldSpecified;
        
        private string baslangicTarihiField;
        
        private string bitisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GorevTur
        {
            get
            {
                return this.gorevTurField;
            }
            set
            {
                this.gorevTurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long GorevBirim
        {
            get
            {
                return this.gorevBirimField;
            }
            set
            {
                this.gorevBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GorevBirimSpecified
        {
            get
            {
                return this.gorevBirimFieldSpecified;
            }
            set
            {
                this.gorevBirimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string BaslangicTarihi
        {
            get
            {
                return this.baslangicTarihiField;
            }
            set
            {
                this.baslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
        public string BitisTarihi
        {
            get
            {
                return this.bitisTarihiField;
            }
            set
            {
                this.bitisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class IdariPersonelveGorevBilgi
    {
        
        private long kadroBirimField;
        
        private bool kadroBirimFieldSpecified;
        
        private long kadroUnvanIdField;
        
        private bool kadroUnvanIdFieldSpecified;
        
        private string kadroUnvanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long KadroBirim
        {
            get
            {
                return this.kadroBirimField;
            }
            set
            {
                this.kadroBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KadroBirimSpecified
        {
            get
            {
                return this.kadroBirimFieldSpecified;
            }
            set
            {
                this.kadroBirimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long KadroUnvanId
        {
            get
            {
                return this.kadroUnvanIdField;
            }
            set
            {
                this.kadroUnvanIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KadroUnvanIdSpecified
        {
            get
            {
                return this.kadroUnvanIdFieldSpecified;
            }
            set
            {
                this.kadroUnvanIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KadroUnvan
        {
            get
            {
                return this.kadroUnvanField;
            }
            set
            {
                this.kadroUnvanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class AkademikPersonelBilgi
    {
        
        private long kadroBirimField;
        
        private bool kadroBirimFieldSpecified;
        
        private long kadroUnvanIdField;
        
        private bool kadroUnvanIdFieldSpecified;
        
        private string kadroUnvanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long KadroBirim
        {
            get
            {
                return this.kadroBirimField;
            }
            set
            {
                this.kadroBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KadroBirimSpecified
        {
            get
            {
                return this.kadroBirimFieldSpecified;
            }
            set
            {
                this.kadroBirimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long KadroUnvanId
        {
            get
            {
                return this.kadroUnvanIdField;
            }
            set
            {
                this.kadroUnvanIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KadroUnvanIdSpecified
        {
            get
            {
                return this.kadroUnvanIdFieldSpecified;
            }
            set
            {
                this.kadroUnvanIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KadroUnvan
        {
            get
            {
                return this.kadroUnvanField;
            }
            set
            {
                this.kadroUnvanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class KisiselBilgi
    {
        
        private long tcKimlikNoField;
        
        private bool tcKimlikNoFieldSpecified;
        
        private string adiField;
        
        private string soyadiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TcKimlikNoSpecified
        {
            get
            {
                return this.tcKimlikNoFieldSpecified;
            }
            set
            {
                this.tcKimlikNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Adi
        {
            get
            {
                return this.adiField;
            }
            set
            {
                this.adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Soyadi
        {
            get
            {
                return this.soyadiField;
            }
            set
            {
                this.soyadiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class AkademikveIdariPersonelResponseType
    {
        
        private KisiselBilgi kisiselField;
        
        private AkademikPersonelBilgi akademikPersonelField;
        
        private IdariPersonelveGorevBilgi[] idariPersonelveGorevField;
        
        private GorevlendirmeBilgi[] gorevlendirmeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KisiselBilgi Kisisel
        {
            get
            {
                return this.kisiselField;
            }
            set
            {
                this.kisiselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AkademikPersonelBilgi AkademikPersonel
        {
            get
            {
                return this.akademikPersonelField;
            }
            set
            {
                this.akademikPersonelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdariPersonelveGorev", Order=2)]
        public IdariPersonelveGorevBilgi[] IdariPersonelveGorev
        {
            get
            {
                return this.idariPersonelveGorevField;
            }
            set
            {
                this.idariPersonelveGorevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Gorevlendirme", Order=3)]
        public GorevlendirmeBilgi[] Gorevlendirme
        {
            get
            {
                return this.gorevlendirmeField;
            }
            set
            {
                this.gorevlendirmeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03")]
    public partial class AkademikveIdariPersonelResponse
    {
        
        private AkademikveIdariPersonelResponseType akademikveIdariPersonelField;
        
        private ResponseInfoType sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AkademikveIdariPersonelResponseType AkademikveIdariPersonel
        {
            get
            {
                return this.akademikveIdariPersonelField;
            }
            set
            {
                this.akademikveIdariPersonelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseInfoType Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AkademikveIdariPersonelRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03", Order=0)]
        public TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest AkademikveIdariPersonelRequest;
        
        public AkademikveIdariPersonelRequest1()
        {
        }
        
        public AkademikveIdariPersonelRequest1(TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest AkademikveIdariPersonelRequest)
        {
            this.AkademikveIdariPersonelRequest = AkademikveIdariPersonelRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AkademikveIdariPersonelResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/akademikveidaripersonel/2020/03", Order=0)]
        public TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelResponse AkademikveIdariPersonelResponse;
        
        public AkademikveIdariPersonelResponse1()
        {
        }
        
        public AkademikveIdariPersonelResponse1(TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelResponse AkademikveIdariPersonelResponse)
        {
            this.AkademikveIdariPersonelResponse = AkademikveIdariPersonelResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface AkademikveIdariPersonelPortChannel : TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AkademikveIdariPersonelPortClient : System.ServiceModel.ClientBase<TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelPort>, TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AkademikveIdariPersonelPortClient() : 
                base(AkademikveIdariPersonelPortClient.GetDefaultBinding(), AkademikveIdariPersonelPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AkademikveIdariPersonelPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademikveIdariPersonelPortClient(EndpointConfiguration endpointConfiguration) : 
                base(AkademikveIdariPersonelPortClient.GetBindingForEndpoint(endpointConfiguration), AkademikveIdariPersonelPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademikveIdariPersonelPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AkademikveIdariPersonelPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademikveIdariPersonelPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AkademikveIdariPersonelPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademikveIdariPersonelPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelResponse1> TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelPort.AkademikveIdariPersonelAsync(TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest1 request)
        {
            return base.Channel.AkademikveIdariPersonelAsync(request);
        }
        
        public System.Threading.Tasks.Task<TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelResponse1> AkademikveIdariPersonelAsync(TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest AkademikveIdariPersonelRequest)
        {
            TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest1 inValue = new TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelRequest1();
            inValue.AkademikveIdariPersonelRequest = AkademikveIdariPersonelRequest;
            return ((TcKimlikNoileAkademikIdariPersonelveGorevlendirmeSorgulaV1.AkademikveIdariPersonelPort)(this)).AkademikveIdariPersonelAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AkademikveIdariPersonelPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AkademikveIdariPersonelPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://servis.turkiye.gov.tr/services/g2g/yok/TcKimlikNoileAkademikIdariPersonel" +
                        "veGorevlendirmeSorgulav1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AkademikveIdariPersonelPortClient.GetBindingForEndpoint(EndpointConfiguration.AkademikveIdariPersonelPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AkademikveIdariPersonelPortClient.GetEndpointAddress(EndpointConfiguration.AkademikveIdariPersonelPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            AkademikveIdariPersonelPortSoap11,
        }
    }
}
