//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TariheGoreSaglikMezunlariniSorgulaV1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02", ConfigurationName="TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariPort")]
    public interface SaglikMezunlariPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariResponse1> SaglikMezunlariAsync(TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02")]
    public partial class SaglikMezunlariRequest
    {
        
        private SaglikMezunlariRequestType saglikMezunlariniGetirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SaglikMezunlariRequestType SaglikMezunlariniGetir
        {
            get
            {
                return this.saglikMezunlariniGetirField;
            }
            set
            {
                this.saglikMezunlariniGetirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02")]
    public partial class SaglikMezunlariRequestType
    {
        
        private int mezuniyetGunField;
        
        private int mezuniyetAyField;
        
        private int mezuniyetYilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MezuniyetGun
        {
            get
            {
                return this.mezuniyetGunField;
            }
            set
            {
                this.mezuniyetGunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MezuniyetAy
        {
            get
            {
                return this.mezuniyetAyField;
            }
            set
            {
                this.mezuniyetAyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MezuniyetYil
        {
            get
            {
                return this.mezuniyetYilField;
            }
            set
            {
                this.mezuniyetYilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02")]
    public partial class ResponseInfoType
    {
        
        private int returnCodeField;
        
        private string externalReturnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string ExternalReturnCode
        {
            get
            {
                return this.externalReturnCodeField;
            }
            set
            {
                this.externalReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02")]
    public partial class SaglikMezunlariResponseType
    {
        
        private System.Nullable<long> tcKimlikNoField;
        
        private System.Nullable<long> birimIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> BirimID
        {
            get
            {
                return this.birimIDField;
            }
            set
            {
                this.birimIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02")]
    public partial class SaglikMezunlariResponse
    {
        
        private SaglikMezunlariResponseType[] saglikMezunlariField;
        
        private ResponseInfoType sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SaglikMezunlari", Order=0)]
        public SaglikMezunlariResponseType[] SaglikMezunlari
        {
            get
            {
                return this.saglikMezunlariField;
            }
            set
            {
                this.saglikMezunlariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseInfoType Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaglikMezunlariRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02", Order=0)]
        public TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest SaglikMezunlariRequest;
        
        public SaglikMezunlariRequest1()
        {
        }
        
        public SaglikMezunlariRequest1(TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest SaglikMezunlariRequest)
        {
            this.SaglikMezunlariRequest = SaglikMezunlariRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaglikMezunlariResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/saglikmezunlari/2019/02", Order=0)]
        public TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariResponse SaglikMezunlariResponse;
        
        public SaglikMezunlariResponse1()
        {
        }
        
        public SaglikMezunlariResponse1(TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariResponse SaglikMezunlariResponse)
        {
            this.SaglikMezunlariResponse = SaglikMezunlariResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SaglikMezunlariPortChannel : TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SaglikMezunlariPortClient : System.ServiceModel.ClientBase<TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariPort>, TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SaglikMezunlariPortClient() : 
                base(SaglikMezunlariPortClient.GetDefaultBinding(), SaglikMezunlariPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SaglikMezunlariPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaglikMezunlariPortClient(EndpointConfiguration endpointConfiguration) : 
                base(SaglikMezunlariPortClient.GetBindingForEndpoint(endpointConfiguration), SaglikMezunlariPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaglikMezunlariPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SaglikMezunlariPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaglikMezunlariPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SaglikMezunlariPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaglikMezunlariPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariResponse1> TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariPort.SaglikMezunlariAsync(TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest1 request)
        {
            return base.Channel.SaglikMezunlariAsync(request);
        }
        
        public System.Threading.Tasks.Task<TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariResponse1> SaglikMezunlariAsync(TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest SaglikMezunlariRequest)
        {
            TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest1 inValue = new TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariRequest1();
            inValue.SaglikMezunlariRequest = SaglikMezunlariRequest;
            return ((TariheGoreSaglikMezunlariniSorgulaV1.SaglikMezunlariPort)(this)).SaglikMezunlariAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaglikMezunlariPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaglikMezunlariPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://servis.turkiye.gov.tr/services/g2g/yok/tarihegoresaglikmezunlarinisorgula" +
                        "v1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SaglikMezunlariPortClient.GetBindingForEndpoint(EndpointConfiguration.SaglikMezunlariPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SaglikMezunlariPortClient.GetEndpointAddress(EndpointConfiguration.SaglikMezunlariPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            SaglikMezunlariPortSoap11,
        }
    }
}
