//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02", ConfigurationName="TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmePort")]
    public interface AkademisyenGorevlendirmePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeResponse1> AkademisyenGorevlendirmeAsync(TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02")]
    public partial class AkademisyenGorevlendirmeRequest
    {
        
        private AkademisyenGorevlendirmeRequestType akademisyenGorevlendirmeBilgiGetirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AkademisyenGorevlendirmeRequestType AkademisyenGorevlendirmeBilgiGetir
        {
            get
            {
                return this.akademisyenGorevlendirmeBilgiGetirField;
            }
            set
            {
                this.akademisyenGorevlendirmeBilgiGetirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02")]
    public partial class AkademisyenGorevlendirmeRequestType
    {
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02")]
    public partial class ResponseInfoType
    {
        
        private int returnCodeField;
        
        private string externalReturnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string ExternalReturnCode
        {
            get
            {
                return this.externalReturnCodeField;
            }
            set
            {
                this.externalReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02")]
    public partial class AkademisyenGorevlendirmeResponseType
    {
        
        private long tcKimlikNoField;
        
        private System.Nullable<long> kirkB_BirimIdField;
        
        private string kirkB_BaslangicTarihiField;
        
        private string kirkB_BitisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> KirkB_BirimId
        {
            get
            {
                return this.kirkB_BirimIdField;
            }
            set
            {
                this.kirkB_BirimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=2)]
        public string KirkB_BaslangicTarihi
        {
            get
            {
                return this.kirkB_BaslangicTarihiField;
            }
            set
            {
                this.kirkB_BaslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=3)]
        public string KirkB_BitisTarihi
        {
            get
            {
                return this.kirkB_BitisTarihiField;
            }
            set
            {
                this.kirkB_BitisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02")]
    public partial class AkademisyenGorevlendirmeResponse
    {
        
        private AkademisyenGorevlendirmeResponseType akademisyenGorevlendirmeField;
        
        private ResponseInfoType sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AkademisyenGorevlendirmeResponseType AkademisyenGorevlendirme
        {
            get
            {
                return this.akademisyenGorevlendirmeField;
            }
            set
            {
                this.akademisyenGorevlendirmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseInfoType Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AkademisyenGorevlendirmeRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02", Order=0)]
        public TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest AkademisyenGorevlendirmeRequest;
        
        public AkademisyenGorevlendirmeRequest1()
        {
        }
        
        public AkademisyenGorevlendirmeRequest1(TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest AkademisyenGorevlendirmeRequest)
        {
            this.AkademisyenGorevlendirmeRequest = AkademisyenGorevlendirmeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AkademisyenGorevlendirmeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/akademisyengorevlendirme/2019/02", Order=0)]
        public TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeResponse AkademisyenGorevlendirmeResponse;
        
        public AkademisyenGorevlendirmeResponse1()
        {
        }
        
        public AkademisyenGorevlendirmeResponse1(TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeResponse AkademisyenGorevlendirmeResponse)
        {
            this.AkademisyenGorevlendirmeResponse = AkademisyenGorevlendirmeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface AkademisyenGorevlendirmePortChannel : TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AkademisyenGorevlendirmePortClient : System.ServiceModel.ClientBase<TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmePort>, TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AkademisyenGorevlendirmePortClient() : 
                base(AkademisyenGorevlendirmePortClient.GetDefaultBinding(), AkademisyenGorevlendirmePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AkademisyenGorevlendirmePortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenGorevlendirmePortClient(EndpointConfiguration endpointConfiguration) : 
                base(AkademisyenGorevlendirmePortClient.GetBindingForEndpoint(endpointConfiguration), AkademisyenGorevlendirmePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenGorevlendirmePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AkademisyenGorevlendirmePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenGorevlendirmePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AkademisyenGorevlendirmePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenGorevlendirmePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeResponse1> TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmePort.AkademisyenGorevlendirmeAsync(TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest1 request)
        {
            return base.Channel.AkademisyenGorevlendirmeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeResponse1> AkademisyenGorevlendirmeAsync(TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest AkademisyenGorevlendirmeRequest)
        {
            TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest1 inValue = new TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmeRequest1();
            inValue.AkademisyenGorevlendirmeRequest = AkademisyenGorevlendirmeRequest;
            return ((TcKimlikNoileAkademisyenGorevlendirmeSorgulaV1.AkademisyenGorevlendirmePort)(this)).AkademisyenGorevlendirmeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AkademisyenGorevlendirmePortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AkademisyenGorevlendirmePortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://servis.turkiye.gov.tr/services/g2g/yok/tckimliknoileakademisyengorevlendi" +
                        "rmesorgulav1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AkademisyenGorevlendirmePortClient.GetBindingForEndpoint(EndpointConfiguration.AkademisyenGorevlendirmePortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AkademisyenGorevlendirmePortClient.GetEndpointAddress(EndpointConfiguration.AkademisyenGorevlendirmePortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            AkademisyenGorevlendirmePortSoap11,
        }
    }
}
