//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSorgulamav2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2", ConfigurationName="MezunSorgulamav2.MezunOgrenciv2_PortType")]
    public interface MezunOgrenciv2_PortType
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="WSDLs_Ogrenci_MezunOgrenciv2_Binder_TcKimlikNoilMezunOgrenciSorgulav2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MezunSorgulamav2.TcKimlikNoilMezunOgrenciSorgulav2Response> TcKimlikNoilMezunOgrenciSorgulav2Async(MezunSorgulamav2.TcKimlikNoilMezunOgrenciSorgulav2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2")]
    public partial class MezunOgrenciv2
    {
        
        private System.Nullable<long> tCKNOField;
        
        private string aDIField;
        
        private string sOYADIField;
        
        private string aNNE_ADIField;
        
        private string bABA_ADIField;
        
        private Tarih dOGUM_TARIHIField;
        
        private Tarih mEZUNIYET_TARIHIField;
        
        private System.Nullable<double> dIPLOMA_NOTUField;
        
        private System.Nullable<int> dIPLOMA_NOT_SISTEMIField;
        
        private string dIPLOMA_NOField;
        
        private string uNIVERSITE_ADIField;
        
        private string fAK_MYO_YO_ENSField;
        
        private string pROGRAM_ADIField;
        
        private System.Nullable<long> uNIV_IDField;
        
        private System.Nullable<long> bIRIM_IDField;
        
        private System.Nullable<long> aLT_PROGRAMField;
        
        private string dURUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> TCKNO
        {
            get
            {
                return this.tCKNOField;
            }
            set
            {
                this.tCKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ADI
        {
            get
            {
                return this.aDIField;
            }
            set
            {
                this.aDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string SOYADI
        {
            get
            {
                return this.sOYADIField;
            }
            set
            {
                this.sOYADIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ANNE_ADI
        {
            get
            {
                return this.aNNE_ADIField;
            }
            set
            {
                this.aNNE_ADIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string BABA_ADI
        {
            get
            {
                return this.bABA_ADIField;
            }
            set
            {
                this.bABA_ADIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public Tarih DOGUM_TARIHI
        {
            get
            {
                return this.dOGUM_TARIHIField;
            }
            set
            {
                this.dOGUM_TARIHIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public Tarih MEZUNIYET_TARIHI
        {
            get
            {
                return this.mEZUNIYET_TARIHIField;
            }
            set
            {
                this.mEZUNIYET_TARIHIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<double> DIPLOMA_NOTU
        {
            get
            {
                return this.dIPLOMA_NOTUField;
            }
            set
            {
                this.dIPLOMA_NOTUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> DIPLOMA_NOT_SISTEMI
        {
            get
            {
                return this.dIPLOMA_NOT_SISTEMIField;
            }
            set
            {
                this.dIPLOMA_NOT_SISTEMIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string DIPLOMA_NO
        {
            get
            {
                return this.dIPLOMA_NOField;
            }
            set
            {
                this.dIPLOMA_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string UNIVERSITE_ADI
        {
            get
            {
                return this.uNIVERSITE_ADIField;
            }
            set
            {
                this.uNIVERSITE_ADIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string FAK_MYO_YO_ENS
        {
            get
            {
                return this.fAK_MYO_YO_ENSField;
            }
            set
            {
                this.fAK_MYO_YO_ENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string PROGRAM_ADI
        {
            get
            {
                return this.pROGRAM_ADIField;
            }
            set
            {
                this.pROGRAM_ADIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public System.Nullable<long> UNIV_ID
        {
            get
            {
                return this.uNIV_IDField;
            }
            set
            {
                this.uNIV_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public System.Nullable<long> BIRIM_ID
        {
            get
            {
                return this.bIRIM_IDField;
            }
            set
            {
                this.bIRIM_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public System.Nullable<long> ALT_PROGRAM
        {
            get
            {
                return this.aLT_PROGRAMField;
            }
            set
            {
                this.aLT_PROGRAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string DURUM
        {
            get
            {
                return this.dURUMField;
            }
            set
            {
                this.dURUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2")]
    public partial class Tarih
    {
        
        private System.Nullable<int> gUNField;
        
        private System.Nullable<int> ayField;
        
        private System.Nullable<int> yILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> GUN
        {
            get
            {
                return this.gUNField;
            }
            set
            {
                this.gUNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> AY
        {
            get
            {
                return this.ayField;
            }
            set
            {
                this.ayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> YIL
        {
            get
            {
                return this.yILField;
            }
            set
            {
                this.yILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2")]
    public partial class Sonuc
    {
        
        private string durumAciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string DurumAciklama
        {
            get
            {
                return this.durumAciklamaField;
            }
            set
            {
                this.durumAciklamaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TcKimlikNoilMezunOgrenciSorgulav2", WrapperNamespace="http://servisler.yok.gov.tr/MezunOgrenciv2", IsWrapped=true)]
    public partial class TcKimlikNoilMezunOgrenciSorgulav2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<long> TCKNO;
        
        public TcKimlikNoilMezunOgrenciSorgulav2Request()
        {
        }
        
        public TcKimlikNoilMezunOgrenciSorgulav2Request(System.Nullable<long> TCKNO)
        {
            this.TCKNO = TCKNO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TcKimlikNoilMezunOgrenciSorgulav2Response", WrapperNamespace="http://servisler.yok.gov.tr/MezunOgrenciv2", IsWrapped=true)]
    public partial class TcKimlikNoilMezunOgrenciSorgulav2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MEZUN_OGRENCI_KAYITLARI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MezunSorgulamav2.MezunOgrenciv2[] MEZUN_OGRENCI_KAYITLARI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.yok.gov.tr/MezunOgrenciv2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MezunSorgulamav2.Sonuc SONUC;
        
        public TcKimlikNoilMezunOgrenciSorgulav2Response()
        {
        }
        
        public TcKimlikNoilMezunOgrenciSorgulav2Response(MezunSorgulamav2.MezunOgrenciv2[] MEZUN_OGRENCI_KAYITLARI, MezunSorgulamav2.Sonuc SONUC)
        {
            this.MEZUN_OGRENCI_KAYITLARI = MEZUN_OGRENCI_KAYITLARI;
            this.SONUC = SONUC;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface MezunOgrenciv2_PortTypeChannel : MezunSorgulamav2.MezunOgrenciv2_PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MezunOgrenciv2_PortTypeClient : System.ServiceModel.ClientBase<MezunSorgulamav2.MezunOgrenciv2_PortType>, MezunSorgulamav2.MezunOgrenciv2_PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MezunOgrenciv2_PortTypeClient() : 
                base(MezunOgrenciv2_PortTypeClient.GetDefaultBinding(), MezunOgrenciv2_PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSDLs_Ogrenci_MezunOgrenciv2_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MezunOgrenciv2_PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(MezunOgrenciv2_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), MezunOgrenciv2_PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MezunOgrenciv2_PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MezunOgrenciv2_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MezunOgrenciv2_PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MezunOgrenciv2_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MezunOgrenciv2_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MezunSorgulamav2.TcKimlikNoilMezunOgrenciSorgulav2Response> TcKimlikNoilMezunOgrenciSorgulav2Async(MezunSorgulamav2.TcKimlikNoilMezunOgrenciSorgulav2Request request)
        {
            return base.Channel.TcKimlikNoilMezunOgrenciSorgulav2Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSDLs_Ogrenci_MezunOgrenciv2_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSDLs_Ogrenci_MezunOgrenciv2_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://servis.turkiye.gov.tr/services/g2g/yok/mezunsorgulamav2");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MezunOgrenciv2_PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.WSDLs_Ogrenci_MezunOgrenciv2_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MezunOgrenciv2_PortTypeClient.GetEndpointAddress(EndpointConfiguration.WSDLs_Ogrenci_MezunOgrenciv2_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            WSDLs_Ogrenci_MezunOgrenciv2_Port,
        }
    }
}
