//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcKimlikNoileAkademisyenUzmanlikSorgulaV1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02", ConfigurationName="TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikPort")]
    public interface AkademisyenUzmanlikPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikResponse1> AkademisyenUzmanlikAsync(TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02")]
    public partial class AkademisyenUzmanlikRequest
    {
        
        private AkademisyenUzmanlikRequestType akademisyenUzmanlikBilgiGetirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AkademisyenUzmanlikRequestType AkademisyenUzmanlikBilgiGetir
        {
            get
            {
                return this.akademisyenUzmanlikBilgiGetirField;
            }
            set
            {
                this.akademisyenUzmanlikBilgiGetirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02")]
    public partial class AkademisyenUzmanlikRequestType
    {
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02")]
    public partial class ResponseInfoType
    {
        
        private int returnCodeField;
        
        private string externalReturnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string ExternalReturnCode
        {
            get
            {
                return this.externalReturnCodeField;
            }
            set
            {
                this.externalReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02")]
    public partial class AkademisyenUzmanlikResponseType
    {
        
        private long tcKimlikNoField;
        
        private string tUSField;
        
        private string yDUS1Field;
        
        private string yDUS2Field;
        
        private string dUSField;
        
        private string eUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string TUS
        {
            get
            {
                return this.tUSField;
            }
            set
            {
                this.tUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string YDUS1
        {
            get
            {
                return this.yDUS1Field;
            }
            set
            {
                this.yDUS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string YDUS2
        {
            get
            {
                return this.yDUS2Field;
            }
            set
            {
                this.yDUS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string DUS
        {
            get
            {
                return this.dUSField;
            }
            set
            {
                this.dUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string EUS
        {
            get
            {
                return this.eUSField;
            }
            set
            {
                this.eUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02")]
    public partial class AkademisyenUzmanlikResponse
    {
        
        private AkademisyenUzmanlikResponseType akademisyenUzmanlikField;
        
        private ResponseInfoType sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AkademisyenUzmanlikResponseType AkademisyenUzmanlik
        {
            get
            {
                return this.akademisyenUzmanlikField;
            }
            set
            {
                this.akademisyenUzmanlikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseInfoType Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AkademisyenUzmanlikRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02", Order=0)]
        public TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest AkademisyenUzmanlikRequest;
        
        public AkademisyenUzmanlikRequest1()
        {
        }
        
        public AkademisyenUzmanlikRequest1(TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest AkademisyenUzmanlikRequest)
        {
            this.AkademisyenUzmanlikRequest = AkademisyenUzmanlikRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AkademisyenUzmanlikResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/akademisyenuzmanlik/2019/02", Order=0)]
        public TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikResponse AkademisyenUzmanlikResponse;
        
        public AkademisyenUzmanlikResponse1()
        {
        }
        
        public AkademisyenUzmanlikResponse1(TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikResponse AkademisyenUzmanlikResponse)
        {
            this.AkademisyenUzmanlikResponse = AkademisyenUzmanlikResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface AkademisyenUzmanlikPortChannel : TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AkademisyenUzmanlikPortClient : System.ServiceModel.ClientBase<TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikPort>, TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AkademisyenUzmanlikPortClient() : 
                base(AkademisyenUzmanlikPortClient.GetDefaultBinding(), AkademisyenUzmanlikPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AkademisyenUzmanlikPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenUzmanlikPortClient(EndpointConfiguration endpointConfiguration) : 
                base(AkademisyenUzmanlikPortClient.GetBindingForEndpoint(endpointConfiguration), AkademisyenUzmanlikPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenUzmanlikPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AkademisyenUzmanlikPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenUzmanlikPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AkademisyenUzmanlikPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AkademisyenUzmanlikPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikResponse1> TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikPort.AkademisyenUzmanlikAsync(TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest1 request)
        {
            return base.Channel.AkademisyenUzmanlikAsync(request);
        }
        
        public System.Threading.Tasks.Task<TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikResponse1> AkademisyenUzmanlikAsync(TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest AkademisyenUzmanlikRequest)
        {
            TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest1 inValue = new TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikRequest1();
            inValue.AkademisyenUzmanlikRequest = AkademisyenUzmanlikRequest;
            return ((TcKimlikNoileAkademisyenUzmanlikSorgulaV1.AkademisyenUzmanlikPort)(this)).AkademisyenUzmanlikAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AkademisyenUzmanlikPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AkademisyenUzmanlikPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://servis.turkiye.gov.tr/services/g2g/yok/tckimliknoileakademisyenuzmanlikso" +
                        "rgulav1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AkademisyenUzmanlikPortClient.GetBindingForEndpoint(EndpointConfiguration.AkademisyenUzmanlikPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AkademisyenUzmanlikPortClient.GetEndpointAddress(EndpointConfiguration.AkademisyenUzmanlikPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            AkademisyenUzmanlikPortSoap11,
        }
    }
}
